### ISSUE TITLE
broken figures in BLR

### ISSUE THREAD

**Issue by myrmoteras** [plazi/GoldenGATE-Imagine#14]
here are some broken figures
https://zenodo.org/record/155514#.YFL7lK9Kj8A  from an early issue of Zootaxa: FFF0FFA9FFA0FFAFFF8D7628E16CFFAE

**Comment by gsautter** [comment]
Looks as though the article proper was linked to the Zenodo sandbox ... a very early problem ... fixed and cleaned up now.

Hard to tell how the sandbox DOI actually ended up written back to the IMF ... most likely some very early lack of filtering.
