### ISSUE TITLE
detect document structure menu disabled?

### ISSUE THREAD

**Issue by myrmoteras** [plazi/GoldenGATE-Imagine#16]
@gsautter why is the menue detect document structure not here anymore?

![image](https://user-images.githubusercontent.com/4609956/116198605-72248280-a736-11eb-8482-b6af900ca825.png)
[jbacter00390-0321.pdf](https://github.com/plazi/GoldenGATE-Imagine/files/6382521/jbacter00390-0321.pdf)

**Comment by gsautter** [comment]
The "Tools" menu doesn't really look like the way it's configured, either ... there should be more tools, and some of them should be in sub menus ... looks like something might have gone wrong loading GGI, or with an update (structuring the menu with sub menus is a core update).

This has nothing to do with the specific document you open, as the menus are assembled independent of (and before) that, so the best clue should be the log files ... they should indicate what exactly went wrong when loading GGI (if maybe not with the preceding update).

**Comment by myrmoteras** [comment]
here is the log 
[GgImagine.20210427-0848.out.zip](https://github.com/plazi/GoldenGATE-Imagine/files/6387607/GgImagine.20210427-0848.out.zip)

**Comment by gsautter** [comment]
Thanks for this ... looks as though the `Gamta.jar` in this installation is either heavily outdated or simply broken, and as a result several elements of the document style templates are missing ... could you please check the following:
- When was the `Gamta.jar` in this installation last changed?
- What size in bytes does the `Gamta.jar` in this installation have?
- Can you open the `Gamta.jar` in this installation with WinZip or something similar?

**Comment by myrmoteras** [comment]
> it is the gamta.jar i got a couple of days ago from thd ggi version we have for download

will get you details tomorrow

**Comment by gsautter** [comment]
Either way, here are the latest GGI updates ... those should fix it (install top to bottom):
- http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20210409-0114.zip
- http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20210412-2126.zip
- http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20210415-1630.zip

**Comment by myrmoteras** [comment]
Sorry
I am lost, and now I can't even open the GGI anymore. Please let me know when you have a moment to got through this and get me set up again
tx
d

[GgImagine.20210428-0928.err.zip](https://github.com/plazi/GoldenGATE-Imagine/files/6389888/GgImagine.20210428-0928.err.zip)

**Comment by gsautter** [comment]
Not sure what exactly there might have gone wrong with these online updates, but the error log indicates that still some part of `Gamta.jar` is missing ... 
If you download and unzip http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20210415-1630.zip into your GGI root folder, it _should work as normal ... the contained `Gamta.jar` should have 1,742,653 bytes.

**Comment by myrmoteras** [comment]
does not work:
[GgImagine.20210428-1313.out.zip](https://github.com/plazi/GoldenGATE-Imagine/files/6391418/GgImagine.20210428-1313.out.zip)

**Comment by gsautter** [comment]
Not yet ... but definitely looks like progress ... now we're only missing some part of `ImageMarkup.jar` ... the latest version  is available from http://tb.plazi.org/GgServer/Updates/GgUpdate.IM.20210412-2126.zip

**Comment by gsautter** [comment]
Sorted out via Skype
