### ISSUE TITLE
question: which repository is the GoldenGATE-Imagine software in production?

### ISSUE THREAD

**Issue by jhpoelen** [plazi/GoldenGATE-Imagine#20]
I noticed that GoldenGate-Imagine hosts here https://github.com/plazi/GoldenGATE-Imagine was last updated many years ago, while @gsautter 's https://github.com/gsautter/GoldenGATE-Imagine . 

Which one is used in existing Plazi workflows?

**Comment by gsautter** [comment]
This one is more recent: https://github.com/gsautter/goldengate-imagine ... if you have specific question, feel free to ask.

**Comment by jhpoelen** [comment]
@gsautter thanks! Would it be an idea to update the Readme of Plazi's out dated copy to point folks like me into the right direction?

**Comment by jhpoelen** [comment]
@gsautter I do have a question - I just added a high-level provenance chain for the Treatment XML files at https://www.globalbioticinteractions.org/plazi-zenodo/#plazi-transcription-provenance . This includes your GoldenGATE Imagine tools. Please let me know if I missed any Plazi tools in this simplified version of your workflow.

**Comment by gsautter** [comment]
The relationship graph is almost correct, just one little thing: the desktop applications in data production work at the article level (that's where content coherence is, as well as metadata, bibliography, etc.), it's only TreatmentBank that chops the articles into treatments and offers them individually.
Downstream third-party tools would, as you correctly depict, take it from there and work on individual treatments, though.
