### ISSUE TITLE
font issue: Taiwania FFB22A46CA5DFFC1316EFF91E13FFFB8

### ISSUE THREAD

**Issue by myrmoteras** [plazi/GoldenGATE-Imagine#29]
@gsautter I was exploring the BLR webhook, and got the following result FFB22A46CA5DFFC1316EFF91E13FFFB8

![image](https://user-images.githubusercontent.com/4609956/208655628-bda5d6c1-2078-4f3d-be71-cb390559ada7.png) 

FF9EFF89FF9F1929FFEFA02AD3271041
![image](https://user-images.githubusercontent.com/4609956/208700441-46448487-97be-4181-92aa-e90a1a04938c.png)

**Comment by gsautter** [comment]
That sure looks like a font issue ... will check,

**Comment by gsautter** [comment]
Figured it out ... the characters given in the PDF proper did correctly map to the glyphs in the fonts ... only the Unicode mapping has a decoding issue, which I fixed now ... a respective update is out.
