### ISSUE TITLE
Post manual/usage documentation

### ISSUE THREAD

**Issue by tcatapano** [plazi/GoldenGATE-Imagine#3]
A PDF Should either be included in future releases and online through derived html pages (using github pages, perhaps)

**Comment by gsautter** [comment]
Not sure how to export a PDF from a Google Doc. However, if you show me that, I'll gladly include a PDF manual in the release ZIP. Just a line to add to the config of the tool that does the packaging.

**Comment by myrmoteras** [comment]
I think, it is the command “print” and you’ll get a pdf

**Comment by tcatapano** [comment]
This issue isn't assigned to anyone, Just noting a need. I'll end up taking care of it.

**Comment by tcatapano** [comment]
I've posted a pdf of the manual to the master branch.

**Comment by tcatapano** [comment]
Posted the current version of the manual from Google Docs. Closing.
