### ISSUE TITLE
GGI display issue: page images do not displayed properly

### ISSUE THREAD

**Issue by myrmoteras** [plazi/GoldenGATE-Imagine#31]
in this case of a BHL file, some pages are obscured, alhthough the undelying text is ok.
Is this something that can easily be fixed? If not, then an alternative is to run the files through ABBYY and also resolve some other issues. I will also ask Martin at BHL whether they have journals re-ocred now.

![image](https://user-images.githubusercontent.com/4609956/208854413-e336b681-02fa-49a6-8be8-fceb2d4deb7e.png)

`Edolius Rangoonensis. Ed. ater viridi splendens; rectricum ex-
ternarum scapis longissimis, vexillis late spatulatis ad apicis mar-
ginem exteriorem prcsditis.
Long. tot. (rectricibus externis exclusis) 1 2 unc.; rostri, \\; ala, 6; caudce, 54; tarsi, 1
Rostrum pedesc^e nigri.
Hab. apud Rangoon.
Distinguishable from Ed. Malabaricus, to which it is nearly allied, by its shorter beak, and by the total absence from its forehead of the fine curled plumes which decorate that bird; the wing is also somewhat shorter.
Edolius Crishna. Ed. velutino-ater viridi metallic^ (preesertim ad alas) splendens; gutturis plumis sublanceolatis, viridibus; capite pilis longissimis pluribus ornato; rectricum externarum vexillis spiraliter intortis.
Long. tot. (rectricibus externis exclusis) 12 unc.; rostri, H; al<e, 7; caudce, 6; tarsi, 1
Crishna Crow, Lath., Hist.
Hab. in Nepalid.
The bill of this species is more cultratcd and lengthened than is usual in the geuus. The outer feathers of the tail, which are spi-`

[procZSocLondon.36.5-8.pdf](https://github.com/plazi/GoldenGATE-Imagine/files/10275810/procZSocLondon.36.5-8.pdf)

[procZSocLondon.36.5-8.pdf.imdir.zip](https://github.com/plazi/GoldenGATE-Imagine/files/10275808/procZSocLondon.36.5-8.pdf.imdir.zip)

**Comment by myrmoteras** [comment]
one more 
![image](https://user-images.githubusercontent.com/4609956/208888161-739df467-b538-405f-90e9-904705dcbc40.png)
[revuesuissedezoo28schw.449-451.pdf](https://github.com/plazi/GoldenGATE-Imagine/files/10277030/revuesuissedezoo28schw.449-451.pdf)
[revuesuissedezoo28schw.449-451.pdf.imdir.zip](https://github.com/plazi/GoldenGATE-Imagine/files/10277035/revuesuissedezoo28schw.449-451.pdf.imdir.zip)

**Comment by gsautter** [comment]
Looks like the page image comes up inverted ... digging in.

**Comment by gsautter** [comment]
Adding inversion awareness for JBIG2 encoded mask images did the trick ... tiny issue with the adjustment of words to the page image left to investigate.

**Comment by myrmoteras** [comment]
very good - let me know when this is done and the new build up - wannna play with this.. thanks

**Comment by gsautter** [comment]
Finally figured out and fixed the OCR adjustment problem as well and put out an update.

What was the issue? Well, turns out in none of the original test document for the OCR adjustment were embedded OCR words of a single line so vertically misplaced that they didn't add left to right, but as two lines ... which had the line expand leftwards _after_ there were words associated with it, pulling the (line relative) boundaries of the latter out of place ... added compensation for that now.
