### ISSUE TITLE
Missing Figures

### ISSUE THREAD

**Issue by millerjeremya** [plazi/GoldenGATE-Imagine#49]
@myrmoteras @FLSimoes
This treatment appears to be missing it's figures. 
https://treatment.plazi.org/id/A810F277-7419-D026-FB6B-FC6E9122BB1B
Thanks for some help with troubleshooting. 
![image](https://github.com/plazi/GoldenGATE-Imagine/assets/4322250/821defa5-baef-4dbc-ae3a-e9ab955fc1d3)

**Comment by millerjeremya** [comment]
Pause. This might be only a temporary issue related to activity at Zenodo. Broken figure links on TB are widespread today.

**Comment by myrmoteras** [comment]
yes, the move Zenodo to the new Operating System

**Comment by millerjeremya** [comment]
confirmed, figures in question are back
