### ISSUE TITLE
GGI build of Oct 27 checkin does not build under Ubuntu 14.04 linux with latest Oracle jdk1.8

### ISSUE THREAD

**Issue by ramorrismorris** [plazi/GoldenGATE-Imagine#5]
ant compile
provokes the errors in the attached compile.txt

Missing packages and other compilation errors begin on line 305. Up to there it is UTF8 warnings about encoding of the umlaut in Universit�t in the license.  I will look into that---perhaps the un-tarring needs an option about encoding.  The rest seem to be missing and/or out of date packages

[compile.txt](https://github.com/plazi/GoldenGATE-Imagine/files/52324/compile.txt)

**Comment by gsautter** [comment]
Setting the encoding to ANSI should do the trick. Is there a respective option for Ant?

I guess I should just remove that diacritic from the code, even though it's in a comment. Several hundred files to update ... but Notepad++ should be able to do that fairly quickly.

**Comment by ramorrismorris** [comment]
If you use Java UTF escapes \u00XY  the problem goes away.  If that is what you are in fact doing, I am unsure where the problem lies.  I edited these two lines in GoldenGateImagine.java to become as below and the problem goes away for me

 UNIVERSIT\u00e4 
"\u00A9 by Guido Sautter 2006-" + yearTimestamper.format(new Date()) + "\n" +

**Comment by gsautter** [comment]
OK, will adjust the master branch accordingly.

I guess the umlaut in the license text does look odd, but doesn't bug Ant?

**Comment by ramorrismorris** [comment]
That seems best.  I found it is possible to make the warnings go away by adding
encoding="ISO-8859-1"
to the javac element of javac.ant
but UTF-8 all around is probably what more people need.  Possibly for strict compilers encoding="UTF-8" may still need to go in the ant file.

Now for the errors: At a glance it looks like 13 packages are missing and 57 unresolved symbols in DocumentMetaDataEditorProvider.java

**Comment by gsautter** [comment]
I think it's best to stick with ASCII7 in code anyway ...

As to DocumentMetaDataEditorProvider.java, could you send me an error log? That should tell me what's missing right away.

**Comment by ramorrismorris** [comment]
[compile.txt](https://github.com/plazi/GoldenGATE-Imagine/files/52484/compile.txt)
The attached has the compilation errors

**Comment by gsautter** [comment]
Thanks, that shed all the light required. `BibRefUtils.jar` was missing from the `lib` folder. I've added it now.

**Comment by ramorrismorris** [comment]
Thanks. Making progress.
ant all   makes no .sh files and I can't see how to invoke dist/GgImagineStarter.jar in a way that finds Parameters.cnf.  For example, from build directory I do 
    ram@milne:java -jar dist/GgImagineStarter.jar
UI comes up and requests permission to connect to net.  Accepting that produces 

GoldenGateImagineStarter: java.io.FileNotFoundException (./Parameters.cnfg (No such file or directory)) while reading GoldenGATE startup parameters.
GoldenGateImagineStarter: command is 'java -jar -Xms128m -Xmx512m GgImagine.jar RUN ONLINE'
GoldenGATE Imagine termined: 1

**Comment by gsautter** [comment]
The `Parameters.cnfg` file is included in the release, and the Ant job should pack it into the ZIP it creates ... did you try to run it directly from the `dist` folder?

Anyway, there are built-in defaults for the memory settings, and the "command is ..." line is perfectly fine. Did the "Select Configuration" dialog come up?

**Comment by ramorrismorris** [comment]
Between clarifying the designed deployment from a rebuild and a few minor UI repairs that @gsautter pushed to github https://github.com/plazi/GoldenGATE-Imagine/commit/fe95ff463e1d29d0c7e35cea5443d66cf89bf799, GGI now builds and deploys under Ubuntu Linux 14.04.  Closing this issue.  Also,  I volunteer to test git commits   as to buildability and startup under Ubuntu Linux.  Thanks Guido.

**Comment by gsautter** [comment]
I've now installed Ant (went surprisingly smooth), tracked and fixed the duplicate JAR issue, and did another `commit` and `push`. Should all be fine now.
