### ISSUE TITLE
extract full date of publication and add to metadata and BLR

### ISSUE THREAD

**Issue by myrmoteras** [plazi/GoldenGATE-Imagine#6]

**Comment by myrmoteras** [comment]
issue: exact publication date for arcticles.

The exact publication date is an important element in taxonomy especially in nomenclature. The date is often published on the front page of an article, such as in Zootaxa



Since we extract the year of the publication, and then set it to the last day of the year in BLR, I would like to suggest that we change this policy wherever we can, especially in those article we extract automatically (Zootaxa, all Pensoft publications).

**Comment by myrmoteras** [comment]
gsautter: I'll try and add that to the bibliographic metadata extractor, as well as to the Zootaxa templates.

**Comment by gsautter** [comment]
This has been resolved with a recent update to the metadata handler.
